version: '3'

services:      
  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M

  pgadmin:
    image: dpage/pgadmin4:5.3
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_volume:/root/.pgadmin
      
      
volumes:
  postgres_volume:
 # pgadmin_volume: