version: '3'

#1. Obraz dockerowy zbudowany za pomocą https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/dockerfiles/18.4.0/Dockerfile.xe
#docker build -t oracle/database:18.4.0-xe -f Dockerfile.xe .

services:      
  oracle:
    image: oracle/database:18.4.0-xe
    environment:
      ORACLE_PWD: mysecurepassword
      ORACLE_CHARACTERSET: AL32UTF8
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./oracle_volume:/opt/oracle/oradata
    ports:
      - 51521:1521
      - 55500:5500
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M